name: Build and deploy .NET Core application to windows webapp BasicProductsApi20230107153921 with API Management Service BasicProductsApiapi
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: BasicProductsApi20230107153921
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: BasicProductsApi
  CONFIGURATION: Release
  AZURE_WEBAPP_PACKAGE_PATH: BasicProductsApi/publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: BasicProductApiResourceGroup
  AZURE_APIM_SERVICENAME: BasicProductsApiapi
  AZURE_APIM_API_ID: BasicProductsApi
  AZURE_APIM_APPSERVICEURL: https://basicproductsapi20230107153921.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 5.6.3
  #SWASHBUCKLE_DOTNET_CORE_VERSION: 3.1.x
  SWASHBUCKLE_DOTNET_CORE_VERSION: 6.x.x
  API_IMPORT_SPECIFICATION_PATH: BasicProductsApi/publish/swagger.json
  API_IMPORT_DLL: BasicProductsApi/publish/BasicProductsApi.dll
  API_IMPORT_VERSION: v1

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build code
        run: |
          dotnet build \
            --configuration $BUILD_CONFIGURATION \
      - name: Package build
        run: |
          dotnet publish $PROJECT_PATH \
            --configuration $BUILD_CONFIGURATION \
            --no-build \
            --output $PUBLISH_PATH
      - name: Store build artefact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: build
#   environment:
#     name: 'production'
#     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#   if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret in GitHub with contents of Publish Profile
          package: ${{ env.PUBLISH_PATH }}
